-- This script was generated by the ERD tool in pgAdmin 4.

BEGIN;


CREATE TABLE IF NOT EXISTS public.course_catalog
(
    year integer,
    term character varying(10) COLLATE pg_catalog."default",
    subject character varying(10) COLLATE pg_catalog."default",
    "number" integer,
    name character varying(255) COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    credit_hours character varying(50) COLLATE pg_catalog."default",
    section_info text COLLATE pg_catalog."default",
    section_title text COLLATE pg_catalog."default",
    section_credit_hours character varying(50) COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS public.course_gen_eds
(
    course_id integer NOT NULL,
    category_code character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT course_gen_eds_pkey PRIMARY KEY (course_id, category_code)
);

CREATE TABLE IF NOT EXISTS public.course_information
(
    year integer,
    term character varying(255) COLLATE pg_catalog."default",
    subject character varying(5) COLLATE pg_catalog."default",
    "number" integer,
    course_title character varying(50) COLLATE pg_catalog."default",
    w integer,
    students integer,
    gpa double precision,
    instructor_id integer,
    course_id integer,
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    CONSTRAINT course_information_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.distinct_courses
(
    subject character varying(255) COLLATE pg_catalog."default",
    "number" integer,
    course_title character varying(255) COLLATE pg_catalog."default",
    id integer NOT NULL DEFAULT nextval('courses_id_seq'::regclass),
    average_gpa double precision,
    was_offered_spring_2026 boolean,
    description text COLLATE pg_catalog."default",
    credit_hours character varying(255) COLLATE pg_catalog."default",
    section_info text COLLATE pg_catalog."default",
    section_title character varying(255) COLLATE pg_catalog."default",
    section_credit_hours character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT courses_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.gen_ed_categories
(
    code character varying(255) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    parent_code character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT gen_ed_categories_pkey PRIMARY KEY (code)
);

CREATE TABLE IF NOT EXISTS public.instructors
(
    id serial NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT instructors_pkey PRIMARY KEY (id),
    CONSTRAINT instructors_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.subjects
(
    code character varying(255) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT subjects_pkey PRIMARY KEY (code)
);

ALTER TABLE IF EXISTS public.course_gen_eds
    ADD CONSTRAINT course_gen_eds_category_code_fkey FOREIGN KEY (category_code)
    REFERENCES public.gen_ed_categories (code) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.course_gen_eds
    ADD CONSTRAINT course_gen_eds_course_id_fkey FOREIGN KEY (course_id)
    REFERENCES public.distinct_courses (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.course_information
    ADD CONSTRAINT fk_course_information_course FOREIGN KEY (course_id)
    REFERENCES public.distinct_courses (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.course_information
    ADD CONSTRAINT fk_instructor FOREIGN KEY (instructor_id)
    REFERENCES public.instructors (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.gen_ed_categories
    ADD CONSTRAINT gen_ed_categories_parent_code_fkey FOREIGN KEY (parent_code)
    REFERENCES public.gen_ed_categories (code) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;